### ISSUE TITLE
Compile/install error

### ISSUE THREAD

**Issue by juli1** [yoogx/ocarina#24]
When issuing make all install, I got the following error:

/usr/bin/install: cannot stat ‘../../../src/python/ocarina_me_aadl_aadl_instances_nodes.py’: No such file or directory
/usr/bin/install: cannot stat ‘../../../src/python/ocarina_me_aadl_aadl_tree_nodes.py’: No such file or directory

**Comment by yoogx** [comment]
This should now be solved with this patch, can you please try?
